### ISSUE TITLE
Interactivity not working

### ISSUE THREAD

**Issue by khaljimbo** [themesberg/tailwind-blazor-starter#3]
Using this getting started repo, or following the instructions here: https://flowbite.com/docs/getting-started/blazor/ the interactivity of the components are not working. 

The CSS and UI components display fine, but nothing happens when clicking on the drop downs. There are no errors or warning appearing in dev tools.

I have tried using CDN version 1.8.0 and 1.8.1 and both Blazor Server and WASM and it is still the same, there is no interactivity on the components.

**Comment by omarqui** [comment]
Yes, I have the same problem!.

**Comment by Sinistancer** [comment]
Is someone planning to fix this issue? I really like this FlowBite and want to try Blazor.

**Comment by fdonnet** [comment]
Same here, not working with Blazor 8.0 (the interactive part)

**Comment by miladsoft** [comment]
To create dropdowns in Blazor, you can use the built-in `InputSelect` component or create custom dropdown components. I'll demonstrate both approaches:

### Using `InputSelect`:

1. In your Blazor component, use the `InputSelect` component for a basic dropdown:

```html
<!-- YourBlazorComponent.razor -->
<label for="fruit">Select a fruit:</label>
<InputSelect id="fruit" @bind-Value="selectedFruit">
    <option value="apple">Apple</option>
    <option value="orange">Orange</option>
    <option value="banana">Banana</option>
</InputSelect>

<p>You selected: @selectedFruit</p>

@code {
    private string selectedFruit;
}
```

In this example, `selectedFruit` is bound to the selected value in the dropdown.

### Creating a Custom Dropdown:

1. Create a new component for your custom dropdown. For example, `CustomDropdown.razor`:

```html
<!-- CustomDropdown.razor -->
<div class="custom-dropdown">
    <button @onclick="ToggleDropdown">Select a fruit</button>
    @if (showDropdown)
    {
        <ul>
            <li @onclick="() => SelectFruit('apple')">Apple</li>
            <li @onclick="() => SelectFruit('orange')">Orange</li>
            <li @onclick="() => SelectFruit('banana')">Banana</li>
        </ul>
    }
</div>

@code {
    private bool showDropdown = false;
    private string selectedFruit;

    private void ToggleDropdown()
    {
        showDropdown = !showDropdown;
    }

    private void SelectFruit(string fruit)
    {
        selectedFruit = fruit;
        showDropdown = false;
    }
}
```

2. Use this custom dropdown component in your main Blazor component:

```html
<!-- YourBlazorComponent.razor -->
<CustomDropdown />
<p>You selected: @selectedFruit</p>

@code {
    private string selectedFruit;
}
```

This custom dropdown uses a button to toggle the visibility of a list of options. When an option is clicked, it updates the `selectedFruit` property and hides the dropdown.

Choose the approach that best fits your needs—whether it's using the built-in `InputSelect` or creating a custom dropdown component. Custom dropdowns offer more flexibility and customization options, but the built-in `InputSelect` is simpler for basic scenarios.

**Comment by miladsoft** [comment]
To show a modal in a Blazor application, you can use a combination of Razor components, CSS for styling, and JavaScript for handling the modal's visibility. Here's a basic example of how you can create a modal in Blazor:

1. **Create a Modal Component:**
   Create a new Blazor component for your modal. For example, `Modal.razor`:

   ```html
   <!-- Modal.razor -->
   <div class="modal" style="display: @(showModal ? "block" : "none")">
       <div class="modal-content">
           <span class="close" @onclick="CloseModal">&times;</span>
           <p>Your modal content goes here.</p>
       </div>
   </div>

   @code {
       private bool showModal = false;

       private void OpenModal()
       {
           showModal = true;
       }

       private void CloseModal()
       {
           showModal = false;
       }
   ```

2. **Add Styles for the Modal:**
   Add styles for your modal in your CSS file (e.g., `styles.css`):

   ```css
   /* styles.css */
   .modal {
       display: none;
       position: fixed;
       z-index: 1;
       left: 0;
       top: 0;
       width: 100%;
       height: 100%;
       overflow: auto;
       background-color: rgba(0,0,0,0.4);
   }

   .modal-content {
       background-color: #fefefe;
       margin: 15% auto;
       padding: 20px;
       border: 1px solid #888;
       width: 80%;
   }

   .close {
       color: #aaa;
       float: right;
       font-size: 28px;
       font-weight: bold;
   }

   .close:hover,
   .close:focus {
       color: black;
       text-decoration: none;
       cursor: pointer;
   }
   ```

3. **Use the Modal in Your Main Component:**
   Include your modal component in your main component (e.g., `Index.razor`):

   ```html
   <!-- Index.razor -->
   <h1>Hello Blazor!</h1>

   <button @onclick="OpenModal">Open Modal</button>

   <Modal />

   @code {
       private void OpenModal()
       {
           // Call the OpenModal method in the Modal component
           // to show the modal when the button is clicked.
           // This is just an example; you can trigger modal opening
           // based on your specific requirements.
           var modal = new Modal();
           modal.OpenModal();
       }
   ```

4. **Reference the CSS in Your Main Component:**
   Make sure to include the CSS file in your main component to apply the styles:

   ```html
   <!-- Index.razor -->
   @* ... *@
   <style>
       @import "./styles.css";
   </style>
   ```

This example uses a combination of Blazor code and CSS to create a simple modal. Adjust the styles and content based on your specific requirements. You can also explore existing Blazor modal libraries or create more complex modal components based on your needs.
